name: 'VCN Notarize Release Assets'
description: 'Notarizes all the assets of a GitHub release using the VCN tool from CodeNotary.com'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  cnil_host:
    description: 'CNIL host.'
    required: true
  cnil_grpc_port:
    description: 'CNIL gRPC port.'
    required: false
    default: 443
  cnil_grpc_no_tls:
    description: 'Specifies to not use TLS for the VCN notarization/verification.'
    required: false
    default: false
  release_url:
    description: 'The URL of the release.'
    required: true
  github_token:
    description: 'GitHub token. Required for private repositories.'
    required: false
  cnil_api_key:
    description: 'CNIL API key. If specified, the following inputs (i.e. cnil_http_port, cnil_personal_token and cnil_ledger) will be ignored.'
    required: false
  cnil_http_port:
    description: 'CNIL HTTP API port.'
    required: false
    default: 443
  cnil_personal_token:
    description: 'CNIL personal token.'
    required: false
  cnil_ledger:
    description: 'CNIL ledger ID.'
    required: false
runs:
  using: 'docker'
  image: 'docker://codenotary/notarize-release-assets:latest'
  # image: 'Dockerfile'
  args:
    - ${{ inputs.cnil_host }}
    - ${{ inputs.cnil_grpc_port }}
    - ${{ inputs.cnil_grpc_no_tls }}
    - ${{ inputs.release_url }}
    - ${{ inputs.github_token }}
    - ${{ inputs.cnil_api_key }}
    - ${{ inputs.cnil_http_port }}
    - ${{ inputs.cnil_personal_token }}
    - ${{ inputs.cnil_ledger }}